### ISSUE TITLE
Issue regarding viewing the note.

### ISSUE THREAD

**Issue by Shurtu-gal** [s-m33r/vue-ipfs-test-project#3]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/100484401/187761000-12ab6d50-211b-4c6e-897a-09dbfe810d17.png">

[https://github.com/ipfs/js-ipfs/issues/1835#issuecomment-542116920](url)

[https://github.com/ipfs/js-ipfs/issues/1835#issuecomment-886088279](url)

**Comment by s-m33r** [comment]
the view button will be removed in the simpler version, so closing for now.
